### ISSUE TITLE
PendingDeprecationWarnings on Python 3: isAlive() is deprecated, use is_alive() instead

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZODB#263] opened 2019-05-07 15:37 UTC
For example:
```
.//python3.7/site-packages/ZODB/tests/MTStorage.py:224: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
  self.assertFalse(t.isAlive(),
.//python3.7/site-packages/ZODB/tests/PackableStorage.py:315: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
  while thread.isAlive():
.//python3.7/site-packages/ZODB/tests/PackableStorage.py:230: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
  liveness = [t.isAlive() for t in threads]
```

`is_alive` is available in Python 2, so it should be an easy switch.

**Comment by d-maurer** [comment] 2019-05-07 17:18
Jason Madden wrote at 2019-5-7 15:37 +0000:
>For example:
>```
>.//python3.7/site-packages/ZODB/tests/MTStorage.py:224: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
>  self.assertFalse(t.isAlive(),
>.//python3.7/site-packages/ZODB/tests/PackableStorage.py:315: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
>  while thread.isAlive():
>.//python3.7/site-packages/ZODB/tests/PackableStorage.py:230: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
>  liveness = [t.isAlive() for t in threads]
>```
>
>`is_alive` is available in Python 2, so it should be an easy switch.

The switch can be important for older Python 3 versions:

  When moving from Python 2 to Python 3, `threading.Thread.isAlive"
  was renamed to "is_alive" (to be more compatible with PEP 8)
  with an "isAlive = is_alive" for backward compatibility.
  However, the alias "isAlive = is_alive" was forgotten for
  the inherited class `threading.DummyThread` which overrides `is_alive`.
  As a consequence, `DummyThread.isAlive` uses an inappropriate
  `isAlive` (that for `Thread` instead of `DummyThread.is_alive`).

  The problem is fixed in Python 3.8.


I hit this bug using `zope.testrunner`: it was using `isAlive`
and my test suite caused the creation of `DummyThread` instances;
the test run died at the first call to `isAlive`
(-->  "https://github.com/zopefoundation/zope.testrunner/issues/81")

**Comment by jamadden** [comment] 2019-05-07 18:35
These are only in tests, not production code, and we're in control of where the threads come from and the platforms we run on (guaranteed thread support), so I don't have any concerns there.

**Closed** 2019-05-08 14:32 UTC

**Comment by stanislav-web** [comment] 2021-02-23 16:01
Will be fixed soon... i am on it
